services:
  wordpress:
    build:
      context: .
      dockerfile: ./Dockerfile-wordpress
    image: dock-press-wordpress
    restart: always
    ports:
      - 8080:80
    container_name: "dock-press-wordpress"
    hostname: "dock-press-wordpress"
    env_file:
      - "./docker.env"
      - "./wordpress.env"
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', getenv('WP_HOME'));
        define('WP_SITEURL', getenv('WP_SITEURL'));
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes:ro
      - wordpress:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: .
      dockerfile: ./Dockerfile-mysql
    image: dock-press-mysql
    restart: always
    container_name: "dock-press-mysql"
    hostname: "dock-press-mysql"
    env_file:
      - "./docker.env"
      - "./mysql.env"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql:
    name: "dock-press-mysql"
  wordpress:
    name: "dock-press-wordpress"
